# Generated by Django 4.2.3 on 2023-07-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("company_number", models.AutoField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=50)),
                ("about", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IT", "INFORMATION TECHNOLOGY"),
                            ("NIT", "NON INFORMATION TECHNOLOGY"),
                        ],
                        max_length=50,
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
